import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { Readable } from 'node:stream';
import { createHash } from 'node:crypto';
import { afterAll, describe, expect, it } from 'vitest';
import {
  absolutePathFor,
  allocate,
  readStored,
  removeStored,
  renameStored,
  storagePathFor,
  storedFileExists,
  uploadRoot,
  writeStream,
} from '../../src/storage/localDisk.js';

/**
 * Local disk storage.
 *
 * The property that matters is the first one asserted: **nothing of the
 * client's is in the path.** Path traversal is not defended against here by
 * sanitising a filename - it is impossible by construction, because the path is
 * derived from a UUID this process generated and an extension chosen from the
 * sniffed type.
 *
 * The rest is ordinary file handling, tested against the real `UPLOAD_ROOT`
 * under ids nothing else uses, and cleaned up afterwards.
 */

/** Every path this file writes, so the cleanup is exact rather than a wipe. */
const written = [];

/**
 * @param {string} extension
 */
function allocateTracked(extension) {
  const allocation = allocate(extension);
  written.push(allocation.relativePath);
  return allocation;
}

afterAll(async () => {
  await Promise.all(written.map((relativePath) => removeStored(relativePath)));
});

describe('storagePathFor', () => {
  it('derives the whole path from the candidate id', () => {
    expect(
      storagePathFor({ candidateId: 'abcd1234-0000-4000-8000-000000000000', extension: '.pdf' }),
    ).toBe('ab/cd/abcd1234-0000-4000-8000-000000000000.pdf');
  });

  it('fans out on the first four hex characters', () => {
    // A single flat directory with a hundred thousand entries is slow to list
    // and unpleasant on most filesystems. A UUID prefix is uniformly
    // distributed, so it needs no other balancing.
    const first = storagePathFor({ candidateId: '00112233-4444-4555-8666-777788889999', extension: '.txt' });
    expect(first.startsWith('00/11/')).toBe(true);
  });

  it('never produces an absolute path or a parent reference', () => {
    const relativePath = storagePathFor({
      candidateId: 'ffffffff-eeee-4ddd-8ccc-bbbbbbbbbbbb',
      extension: '.docx',
    });
    expect(path.isAbsolute(relativePath)).toBe(false);
    expect(relativePath).not.toContain('..');
  });

  it('resolves inside the upload root, whatever the id looks like', () => {
    // The id is generated by `randomUUID`, so this is belt and braces - but it
    // is the assertion that would fail on the day somebody decides to derive the
    // path from the original filename instead.
    const resolved = path.resolve(
      absolutePathFor(storagePathFor({ candidateId: allocate('.pdf').candidateId, extension: '.pdf' })),
    );
    expect(resolved.startsWith(uploadRoot)).toBe(true);
  });
});

describe('writeStream', () => {
  it('writes the bytes and hashes them in the same pass', async () => {
    const bytes = Buffer.from('Jane Doe\nSenior Backend Engineer\n', 'utf8');
    const { relativePath } = allocateTracked('.txt');

    const result = await writeStream({ source: Readable.from(bytes), relativePath });

    expect(result.byteSize).toBe(bytes.length);
    expect(result.contentSha256).toBe(createHash('sha256').update(bytes).digest('hex'));
    expect(await readStored(relativePath)).toEqual(bytes);
  });

  it('creates the fan-out directories it needs', async () => {
    const { relativePath } = allocateTracked('.txt');
    await writeStream({ source: Readable.from(Buffer.from('x')), relativePath });
    expect(await storedFileExists(relativePath)).toBe(true);
  });

  it('hashes an empty file rather than failing on it', async () => {
    // An empty upload is refused as UNSUPPORTED_FILE_TYPE by the sniffer, which
    // runs after this. Storage should not have its own opinion about it.
    const { relativePath } = allocateTracked('.txt');
    const result = await writeStream({ source: Readable.from([]), relativePath });
    expect(result.byteSize).toBe(0);
    expect(result.contentSha256).toBe(createHash('sha256').update(Buffer.alloc(0)).digest('hex'));
  });
});

describe('renameStored', () => {
  it('moves a file to the extension the sniffer chose', async () => {
    const { relativePath } = allocateTracked('.upload');
    await writeStream({ source: Readable.from(Buffer.from('%PDF-1.4')), relativePath });

    const finalPath = relativePath.replace(/\.upload$/, '.pdf');
    written.push(finalPath);

    expect(await renameStored(relativePath, finalPath)).toBe(finalPath);
    expect(await storedFileExists(relativePath)).toBe(false);
    expect(await storedFileExists(finalPath)).toBe(true);
  });
});

describe('storedFileExists', () => {
  it('is false for a path that was never written', async () => {
    expect(await storedFileExists('zz/zz/nothing-here.pdf')).toBe(false);
  });

  it('is false for a directory', async () => {
    // `stat` succeeds on a directory; a directory is not a CV.
    const { relativePath } = allocateTracked('.txt');
    await writeStream({ source: Readable.from(Buffer.from('x')), relativePath });
    expect(await storedFileExists(path.dirname(relativePath))).toBe(false);
  });
});

describe('removeStored', () => {
  it('deletes a file and reports success', async () => {
    const { relativePath } = allocateTracked('.txt');
    await writeStream({ source: Readable.from(Buffer.from('x')), relativePath });

    expect(await removeStored(relativePath)).toBe(true);
    expect(await storedFileExists(relativePath)).toBe(false);
  });

  it('is a no-op on a file that is already gone', async () => {
    // Both callers have already decided the file is not wanted; an orphan is
    // harmless, and a throw here would turn a successful upload into a failure.
    expect(await removeStored('zz/zz/never-existed.pdf')).toBe(true);
  });
});

describe('readStored', () => {
  it('throws ENOENT for a missing file, so the caller can decide what that means', async () => {
    // A 410 at the retry endpoint and a candidate failure in the worker are
    // different answers to the same fact, so this layer does not choose.
    await expect(readStored('zz/zz/missing.pdf')).rejects.toMatchObject({ code: 'ENOENT' });
  });
});

describe('allocate', () => {
  it('returns a fresh id and the path derived from it', () => {
    const first = allocate('.pdf');
    const second = allocate('.pdf');

    expect(first.candidateId).not.toBe(second.candidateId);
    expect(first.relativePath).toBe(
      storagePathFor({ candidateId: first.candidateId, extension: '.pdf' }),
    );
  });
});

describe('the upload root', () => {
  it('is absolute even when the environment gave a relative path', async () => {
    expect(path.isAbsolute(uploadRoot)).toBe(true);
    // Nothing here should have escaped into a system temp directory.
    const scratch = await mkdtemp(path.join(tmpdir(), 'cv-'));
    expect(uploadRoot.startsWith(scratch)).toBe(false);
    await rm(scratch, { recursive: true, force: true });
  });
});
