import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { Readable } from 'node:stream';
import { afterAll, describe, expect, it } from 'vitest';
import * as localDisk from '../../src/storage/localDisk.js';
import {
  absolutePathFor,
  allocate,
  removeStored,
  storagePathFor,
  storedFileExists,
  uploadRoot,
  writeStream,
} from '../../src/storage/localDisk.js';
import { describeStorageContract } from './storageContract.js';

/**
 * Local disk storage.
 *
 * The property that matters is the first one asserted: **nothing of the
 * client's is in the path.** Path traversal is not defended against here by
 * sanitising a filename - it is impossible by construction, because the path is
 * derived from a UUID this process generated and an extension chosen from the
 * sniffed type.
 *
 * What is left in this file is what is genuinely local: the path rule, the
 * allocator and the upload root. They are pure, and both drivers share the exact
 * same implementation of them, so there is nothing to parameterise.
 *
 * The behavioural assertions moved to `storageContract.js` when the S3 adapter
 * arrived, and are run from the bottom of this file. They are not weaker for
 * having moved - they are the same assertions, now held to by two adapters
 * instead of one.
 */

/** Every path this file writes, so the cleanup is exact rather than a wipe. */
const written = [];

/**
 * @param {string} extension
 */
function allocateTracked(extension) {
  const allocation = allocate(extension);
  written.push(allocation.relativePath);
  return allocation;
}

afterAll(async () => {
  await Promise.all(written.map((relativePath) => removeStored(relativePath)));
});

describe('storagePathFor', () => {
  it('derives the whole path from the candidate id', () => {
    expect(
      storagePathFor({ candidateId: 'abcd1234-0000-4000-8000-000000000000', extension: '.pdf' }),
    ).toBe('ab/cd/abcd1234-0000-4000-8000-000000000000.pdf');
  });

  it('fans out on the first four hex characters', () => {
    // A single flat directory with a hundred thousand entries is slow to list
    // and unpleasant on most filesystems. A UUID prefix is uniformly
    // distributed, so it needs no other balancing.
    const first = storagePathFor({ candidateId: '00112233-4444-4555-8666-777788889999', extension: '.txt' });
    expect(first.startsWith('00/11/')).toBe(true);
  });

  it('never produces an absolute path or a parent reference', () => {
    const relativePath = storagePathFor({
      candidateId: 'ffffffff-eeee-4ddd-8ccc-bbbbbbbbbbbb',
      extension: '.docx',
    });
    expect(path.isAbsolute(relativePath)).toBe(false);
    expect(relativePath).not.toContain('..');
  });

  it('resolves inside the upload root, whatever the id looks like', () => {
    // The id is generated by `randomUUID`, so this is belt and braces - but it
    // is the assertion that would fail on the day somebody decides to derive the
    // path from the original filename instead.
    const resolved = path.resolve(
      absolutePathFor(storagePathFor({ candidateId: allocate('.pdf').candidateId, extension: '.pdf' })),
    );
    expect(resolved.startsWith(uploadRoot)).toBe(true);
  });
});






describe('allocate', () => {
  it('returns a fresh id and the path derived from it', () => {
    const first = allocate('.pdf');
    const second = allocate('.pdf');

    expect(first.candidateId).not.toBe(second.candidateId);
    expect(first.relativePath).toBe(
      storagePathFor({ candidateId: first.candidateId, extension: '.pdf' }),
    );
  });
});

describe('the upload root', () => {
  it('is absolute even when the environment gave a relative path', async () => {
    expect(path.isAbsolute(uploadRoot)).toBe(true);
    // Nothing here should have escaped into a system temp directory.
    const scratch = await mkdtemp(path.join(tmpdir(), 'cv-'));
    expect(uploadRoot.startsWith(scratch)).toBe(false);
    await rm(scratch, { recursive: true, force: true });
  });
});

// The behavioural half, from the shared contract. Every assertion in there also
// runs against the S3 adapter in `storage.s3.test.js`, which is what makes
// "the callers cannot tell the two apart" a tested claim rather than a hope.
describeStorageContract('local disk', localDisk, { allocate });
