/**
 * Labelled inputs.
 *
 * Every control in this application goes through one of these, which is how
 * "every input has an associated label" becomes structural rather than a thing
 * to remember. The id is generated by `useId`, the `<label>` carries `htmlFor`,
 * and hint and error text are wired into `aria-describedby` so a screen reader
 * reads the rule and the failure with the field rather than after it.
 *
 * An invalid field carries `aria-invalid` **and** a visible message **and** a
 * changed border - three signals, because the border alone is colour-only.
 */

import { useId } from 'react';

/**
 * @param {object} props
 * @param {string} props.label
 * @param {string} [props.hint]
 * @param {string | null} [props.error]
 * @param {(ids: { id: string, describedBy: string | undefined, invalid: boolean }) => import('react').ReactNode} props.children
 */
function FieldShell({ label, hint, error, children }) {
  const id = useId();
  const hintId = hint ? `${id}-hint` : null;
  const errorId = error ? `${id}-error` : null;
  const describedBy = [hintId, errorId].filter(Boolean).join(' ') || undefined;

  return (
    <div className="field">
      <label className="field__label" htmlFor={id}>
        {label}
      </label>
      {hint ? (
        <span className="field__hint" id={/** @type {string} */ (hintId)}>
          {hint}
        </span>
      ) : null}
      {children({ id, describedBy, invalid: Boolean(error) })}
      {error ? (
        <span className="field__error" id={/** @type {string} */ (errorId)}>
          {error}
        </span>
      ) : null}
    </div>
  );
}

/**
 * @param {object} props
 * @param {string} props.label
 * @param {string} props.value
 * @param {(value: string) => void} props.onChange
 * @param {string} [props.hint]
 * @param {string | null} [props.error]
 * @param {string} [props.placeholder]
 * @param {number} [props.maxLength]
 * @param {boolean} [props.disabled]
 */
export function TextField({
  label,
  value,
  onChange,
  hint,
  error,
  placeholder,
  maxLength,
  disabled,
}) {
  return (
    <FieldShell label={label} hint={hint} error={error}>
      {({ id, describedBy, invalid }) => (
        <input
          id={id}
          type="text"
          value={value}
          placeholder={placeholder}
          maxLength={maxLength}
          disabled={disabled}
          aria-describedby={describedBy}
          aria-invalid={invalid || undefined}
          onChange={(event) => onChange(event.target.value)}
        />
      )}
    </FieldShell>
  );
}

/**
 * @param {object} props
 * @param {string} props.label
 * @param {number | ''} props.value
 * @param {(value: number | '') => void} props.onChange
 * @param {number} [props.min]
 * @param {number} [props.max]
 * @param {string} [props.hint]
 * @param {string | null} [props.error]
 * @param {boolean} [props.disabled]
 */
export function NumberField({ label, value, onChange, min, max, hint, error, disabled }) {
  return (
    <FieldShell label={label} hint={hint} error={error}>
      {({ id, describedBy, invalid }) => (
        <input
          id={id}
          type="number"
          inputMode="numeric"
          value={value}
          min={min}
          max={max}
          disabled={disabled}
          aria-describedby={describedBy}
          aria-invalid={invalid || undefined}
          onChange={(event) => {
            const raw = event.target.value;
            // An empty box is empty, not zero. Coercing it to 0 would silently
            // make a weight valid and a "years" rule pass at nothing.
            onChange(raw === '' ? '' : Number(raw));
          }}
        />
      )}
    </FieldShell>
  );
}

/**
 * @param {object} props
 * @param {string} props.label
 * @param {string} props.value
 * @param {(value: string) => void} props.onChange
 * @param {string} [props.hint]
 * @param {string | null} [props.error]
 * @param {number} [props.maxLength]
 * @param {boolean} [props.disabled]
 */
export function TextAreaField({ label, value, onChange, hint, error, maxLength, disabled }) {
  return (
    <FieldShell label={label} hint={hint} error={error}>
      {({ id, describedBy, invalid }) => (
        <textarea
          id={id}
          value={value}
          maxLength={maxLength}
          disabled={disabled}
          aria-describedby={describedBy}
          aria-invalid={invalid || undefined}
          onChange={(event) => onChange(event.target.value)}
        />
      )}
    </FieldShell>
  );
}

/**
 * @param {object} props
 * @param {string} props.label
 * @param {string} props.value
 * @param {(value: string) => void} props.onChange
 * @param {Array<{ value: string, label: string }>} props.options
 * @param {string} [props.hint]
 * @param {string | null} [props.error]
 * @param {boolean} [props.disabled]
 */
export function SelectField({ label, value, onChange, options, hint, error, disabled }) {
  return (
    <FieldShell label={label} hint={hint} error={error}>
      {({ id, describedBy, invalid }) => (
        <select
          id={id}
          value={value}
          disabled={disabled}
          aria-describedby={describedBy}
          aria-invalid={invalid || undefined}
          onChange={(event) => onChange(event.target.value)}
        >
          {options.map((option) => (
            <option key={option.value} value={option.value}>
              {option.label}
            </option>
          ))}
        </select>
      )}
    </FieldShell>
  );
}

/**
 * @param {object} props
 * @param {string} props.label
 * @param {boolean} props.checked
 * @param {(checked: boolean) => void} props.onChange
 * @param {boolean} [props.disabled]
 */
export function CheckboxField({ label, checked, onChange, disabled }) {
  const id = useId();
  return (
    <div className="checkbox-field">
      <input
        id={id}
        type="checkbox"
        checked={checked}
        disabled={disabled}
        onChange={(event) => onChange(event.target.checked)}
      />
      <label htmlFor={id}>{label}</label>
    </div>
  );
}
